### PR TITLE
fix: Add animation on scroll library

### PR DESCRIPTION
**Pull request by NataliiaKononikhina**
[JIRA](https://centracommerce.atlassian.net/browse/SHOWROOM-259)

### CODE REVIEW

**Comment by kparzecki** [comment]
In Firefox the image in support section has improper sizing.
image

**Comment by kparzecki** [comment]
On documentation pages images are overflowing on smaller screens.
image

**Comment by kparzecki** [comment]
I think that it would be nice to add some padding below previous/next section buttons on mobile screens.
image

**Comment by NataliiaKononikhina** [comment]
@kparzecki I will work on guides pages later (maybe in 3 weeks).

**Pull request merged**
